version: '3.8'

services:
  react-app:
    build:
      context: ./travel-vibe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./travel-vibe/src:/app/src
      - ./travel-vibe/public:/app/public
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  fastapi-app:
    build:
      context: ./travel-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./travel-backend:/app
    environment:
      - ENV=development
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload